;;; probe.el --- Differential probe of the weekly table model  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Blaine Mooers
;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Commentary:
;; Prints one line per reading or edit of each table file named on the
;; command line.  probe.py prints the same lines from the Python model, so
;; run.sh can diff the two.
;;; Code:
(require 'writing-habit-table)
(defvar probe-out nil)
(defun s (x) (cond ((null x) "None") ((eq x t) "True") ((numberp x) (number-to-string x)) (t x)))
(defun p (&rest a) (push (mapconcat #'s a "|") probe-out))
(defun h (text) (substring (secure-hash 'sha1 (encode-coding-string text 'utf-8)) 0 12))
(defun b (x) (if x "T" "F"))
(defun ev (tb) (mapconcat (lambda (e) (format "%d,%s,%s,%s,%s" (plist-get e :offset) (plist-get e :start) (plist-get e :end) (plist-get e :letter) (plist-get e :section))) (writing-habit-table-events tb) ";"))
(defun secs (tb) (let ((i -1) out) (dolist (r (writing-habit-table-rows tb)) (setq i (1+ i)) (when (eq (writing-habit-table-row-kind r) 'block) (push (format "%d:%s" i (writing-habit-table-row-section r)) out))) (mapconcat #'identity (nreverse out) ";")))
(defun pairs (al) (mapconcat (lambda (c) (format "%s=%s" (car c) (cdr c))) al ";"))
(dolist (f command-line-args-left)
  (let* ((text (with-temp-buffer (let ((coding-system-for-read 'utf-8)) (insert-file-contents f)) (buffer-string)))
         (fresh (lambda () (writing-habit-table-from-text text f)))
         (tb (funcall fresh)))
    (p f "rt" (h (writing-habit-table-to-text tb)) (b (equal (writing-habit-table-to-text tb) text)))
    (p f "kinds" (mapconcat (lambda (r) (symbol-name (writing-habit-table-row-kind r))) (writing-habit-table-rows tb) ","))
    (p f "events" (ev tb))
    (p f "legend" (mapconcat (lambda (e) (format "%s=%s/%s" (nth 0 e) (nth 1 e) (s (nth 2 e)))) (writing-habit-table-legend tb) ";"))
    (p f "code" (or (car (writing-habit-table-code-or-problem tb)) "ERR"))
    (let ((tot (writing-habit-table-totals tb)))
      (p f "tot" "day" (pairs (plist-get tot :day)))
      (p f "tot" "project" (pairs (plist-get tot :project)))
      (p f "tot" "category" (pairs (plist-get tot :category))))
    (p f "ovl" (mapconcat #'identity (writing-habit-table-overlap-lines tb) "\n"))
    (p f "conf" (mapconcat (lambda (c) (format "%d,%d" (car c) (cdr c)))
                           (sort (writing-habit-table-conflicting-cells tb) (lambda (a b) (or (< (car a) (car b)) (and (= (car a) (car b)) (< (cdr a) (cdr b)))))) ";"))
    (p f "used" (mapconcat #'identity (writing-habit-table-used-codes tb) ",") (writing-habit-table-next-free-code tb))
    (dolist (r (writing-habit-table-block-rows tb)) (p f "clear" r (mapconcat #'number-to-string (writing-habit-table-rows-clear-of tb r) ",")))
    (let ((i -1))
      (dolist (r (writing-habit-table-rows tb))
        (setq i (1+ i))
        (let ((kind (writing-habit-table-row-kind r)))
          (when (and (memq kind '(block section)) (writing-habit-table-columns tb))
            (dolist (above '(t nil))
              (let* ((st (writing-habit-table-suggest-times tb i above)) (u (funcall fresh)))
                (condition-case nil
                    (let ((at (writing-habit-table-insert-block u i above (car st) (cdr st))))
                      (p f "ins" i (b above) (car st) (cdr st) at (h (writing-habit-table-to-text u)) (secs u)))
                  (error (p f "ins" i (b above) (car st) (cdr st) "ERR"))))))
          (when (eq kind 'block)
            (dolist (up '(t nil))
              (let ((tg (writing-habit-table-move-target tb i up)))
                (if (null tg) (p f "mv" i (b up) "None")
                  (let* ((u (funcall fresh)) (at (writing-habit-table-move-block u i up)))
                    (p f "mv" i (b up) tg at (h (writing-habit-table-to-text u)) (secs u) (or (car (writing-habit-table-code-or-problem u)) "ERR"))))))
            (let ((u (funcall fresh)))
              (writing-habit-table-remove-block u i)
              (p f "del" i (h (writing-habit-table-to-text u)) (secs u))))
          (when (eq kind 'legend)
            (dolist (up '(t nil))
              (let ((tg (writing-habit-table-legend-move-target tb i up)))
                (if (null tg) (p f "lmv" i (b up) "None")
                  (let* ((u (funcall fresh)) (at (writing-habit-table-move-legend u i up)))
                    (p f "lmv" i (b up) tg at (h (writing-habit-table-to-text u)))))))
            (dolist (above '(t nil))
              (let* ((u (funcall fresh)) (code (writing-habit-table-next-free-code u)))
                (condition-case nil
                    (let ((at (writing-habit-table-insert-legend u i above code "New project, Oct 3" "speculative")))
                      (p f "lins" i (b above) code at (h (writing-habit-table-to-text u))))
                  (error (p f "lins" i (b above) "ERR")))))
            (let* ((u (funcall fresh)) (code (car (writing-habit-table-row-parsed r)))
                   (ch (writing-habit-table-set-legend u i code "Renamed thing" "safe")))
              (p f "setleg" i (b ch) (h (writing-habit-table-to-text u))))
            (let ((u (funcall fresh)) (code (car (writing-habit-table-row-parsed r))))
              (writing-habit-table-remove-legend u i)
              (p f "ldel" i (h (writing-habit-table-to-text u))
                 (writing-habit-table-cells-using tb code)))))
        (p f "candel" i (b (writing-habit-table-can-remove-block tb i)))))
    (let* ((u (funcall fresh)) (code (writing-habit-table-next-free-code u)))
      (unless (string-empty-p code)
        (let ((at (writing-habit-table-insert-legend u nil nil code "" nil)))
          (p f "lins-end" code at (h (writing-habit-table-to-text u))))))
    (when (and (writing-habit-table-block-rows tb) (writing-habit-table-columns tb))
      (let* ((r0 (car (writing-habit-table-block-rows tb))) (col (car (car (writing-habit-table-columns tb))))
             (u (funcall fresh)))
        (p f "set" (b (writing-habit-table-set-cell u r0 col "q")) (h (writing-habit-table-to-text u)))
        (p f "sync1" (b (writing-habit-table-sync-legend u)) (h (writing-habit-table-to-text u)))
        (writing-habit-table-set-cell u r0 col "")
        (p f "sync2" (b (writing-habit-table-sync-legend u)) (h (writing-habit-table-to-text u)))
        (setq u (funcall fresh))
        (p f "setlong" (b (writing-habit-table-set-cell u r0 col "Zebra")) (h (writing-habit-table-to-text u)))))
    (let ((lc (writing-habit-table-legend-check tb)))
      (p f "lcheck" (mapconcat (lambda (r) (mapconcat #'s r ",")) (car lc) ";") (mapconcat #'identity (cadr lc) ",")))
    (p f "dups" (mapconcat (lambda (c) (format "%s=%s" (car c) (mapconcat #'identity (cdr c) "/"))) (writing-habit-table-duplicate-legend-codes tb) ";"))
    (p f "stray" (pairs (writing-habit-table-stray-risk-tags tb)))
    (p f "unk" (mapconcat #'identity (writing-habit-table-unknown-sections tb) ","))
    (dolist (e (writing-habit-table-legend tb))
      (let ((i (writing-habit-table-project-info tb (car e))))
        (p f "info" (car e) (plist-get i :name) (plist-get i :due) (plist-get i :risk))))))
(princ (mapconcat #'identity (nreverse probe-out) "\n")) (terpri)
;;; probe.el ends here
